

function frasesAleatorias(index){
    const frases = [
    "Quem tem luz própria jamais ficará na escuridão. 🌟",
    "Você atingirá o sucesso quando apresentar com orgulho as cicatrizes que adquiriu ao longo da sua jornada.",
    "Quanto mais fortes forem suas provações, maiores serão suas vitórias. 😉",
    "Trabalhar duro te levará para cima, aproveitar o caminho te levará mais longe.",
    "Não espere pelo momento perfeito. Faça de cada momento a oportunidade perfeita.",
    "Vencedores não são pessoas que nunca falham, são pessoas que nunca desistem.🦸‍♂️",
    "Esteja presente em cada momento da sua vida, antes que estes momentos se tornem apenas lembranças.",
    "Viva a história que um dia você gostaria de contar para os seus netos.",
    "Cada falha deixa um ensino, cada ensino deixa uma experiência e cada experiência deixa uma marca. ✨",
    "Procurai suportar com ânimo tudo aquilo que precisa ser feito.",
    "Desconfie do destino e acredite em você. Gaste mais horas realizando que sonhando, fazendo que planejando, vivendo que esperando porque, embora quem quase morre esteja vivo, quem quase vive já morreu.",
    "O sucesso começa onde termina a zona de conforto.",
    "Acredite no poder da persistência.",
    "Você é mais forte do que imagina. Continue!",
    "Grandes conquistas vêm de grandes desafios.",
    "Não pare até se orgulhar.",
    "A jornada pode ser longa, mas vale cada passo.",
    "O único limite para o seu sucesso é a sua determinação.",
    "Acredite em si mesmo e o mundo acreditará em você.",
    "Hoje é o dia perfeito para começar a sua mudança.",
    "Não importa o quão devagar você vá, desde que não pare.",
    "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso.",
    "Os grandes feitos começam com pequenos passos.",
    "Você é capaz de muito mais do que imagina.",
    "Não existe caminho fácil, mas o esforço vale a pena.",
    "Transforme obstáculos em oportunidades.",
    "Acredite que você pode e você já está no meio do caminho.",
    "O segredo da mudança é focar toda a sua energia não no combate ao antigo, mas na construção do novo.",
    "Cada desafio é uma chance de se superar.",
    "O que você faz hoje pode melhorar todos os seus amanhãs.",
    "Faça de cada dia uma obra-prima.",
    "O melhor ainda está por vir.",
    "Não é o que você faz de vez em quando, é o que você faz de forma consistente que traz resultados.",
    "Acredite no poder dos seus sonhos.",
    "Transforme a dor em força e a dificuldade em sabedoria.",
    "O maior risco é não arriscar nada.",
    "O fracasso não é o oposto de sucesso, é parte do sucesso.",
    "Acredite em seu potencial e o resto virá.",
    "Se você não lutar por aquilo que quer, nunca vai conseguir o que merece.",
    "As oportunidades não surgem, elas são criadas.",
    "Seja o tipo de pessoa que você quer encontrar.",
    "Poder é aprender, aprender é poder.",
    "Sua única limitação é a que você coloca em si mesmo.",
    "O caminho para o sucesso é sempre em construção.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Não se preocupe com o que você não pode controlar, concentre-se no que você pode mudar.",
    "Vá além dos seus medos, lá está o seu verdadeiro potencial.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "A única maneira de fazer um excelente trabalho é amar o que você faz.",
    "Viva como se você fosse morrer amanhã. Aprenda como se você fosse viver para sempre.",
    "A maior glória não é nunca cair, mas sim levantar-se a cada vez que caímos.",
    "Às vezes, o maior passo é simplesmente continuar andando.",
    "Seja persistente, mas não teimoso.",
    "Cada erro é uma chance de aprender algo novo.",
    "As melhores coisas da vida acontecem fora da sua zona de conforto.",
    "Não tenha medo de desistir do bom para buscar o ótimo.",
    "O único modo de alcançar o impossível é acreditar que é possível.",
    "O sucesso é um estado de espírito.",
    "Acredite em você e o mundo se abrirá.",
    "Quem não arrisca, não petisca.",
    "Com coragem, você pode transformar qualquer sonho em realidade.",
    "Se você quer algo que nunca teve, faça algo que nunca fez.",
    "A mente que se abre a uma nova ideia jamais volta ao seu tamanho original.",
    "Nada é impossível para quem tem a determinação como aliado.",
    "A única diferença entre você e seus sonhos é a sua capacidade de acreditar neles.",
    "Poderoso é aquele que persevera quando todos ao seu redor desistem.",
    "O sucesso é alcançado por aqueles que não desistem, mesmo quando as circunstâncias pedem para parar.",
    "Não importa o quão difícil seja o caminho, cada passo te leva mais perto do seu destino.",
    "Encare os desafios com coragem e os problemas com confiança.",
    "Não se preocupe com o que você não tem, concentre-se no que você pode conquistar com o que já possui.",
    "Tenha fé em si mesmo, mesmo quando ninguém mais acreditar.",
    "Não é sobre ser o melhor, é sobre ser o seu melhor.",
    "Cada conquista começa com a decisão de tentar.",
    "O único limite que existe é aquele que você coloca em sua mente.",
    "A força de vontade é o combustível do sucesso.",
    "Com trabalho árduo, a vitória é inevitável.",
    "A vitória começa na mente.",
    "O fracasso não é o fim, é o começo de algo novo.",
    "A jornada é tão importante quanto o destino.",
    "Faça o que você pode, com o que você tem, onde você está.",
    "O segredo do sucesso é não ter medo do fracasso.",
    "Acredite que você pode e você já está no meio do caminho.",
    "A vida começa onde sua zona de conforto termina.",
    "Quem não luta por seus sonhos, trabalha para realizar o dos outros.",
    "Acredite que o melhor ainda está por vir.",
    "A persistência é a chave para conquistar aquilo que parece impossível.",
    "Não há sucesso sem sacrifício.",
    "Você nunca sabe o quão forte você é até ser forte é sua única opção.",
    "Os desafios não são obstáculos, são oportunidades disfarçadas.",
    "A maior recompensa vem depois do maior esforço.",
    "A única maneira de alcançar grandes feitos é primeiro acreditar que você pode.",
    "O primeiro passo para alcançar qualquer coisa é acreditar que você é capaz.",
    "Nada acontece até que você se mova.",
    "O sucesso não é para os que nunca falham, mas para os que nunca desistem.",
    "Seja audacioso, seja ousado, seja você.",
    "Às vezes, o maior risco é não correr nenhum risco.",
    "O mundo é dos que fazem acontecer.",
    "Transforme seus sonhos em metas, e suas metas em conquistas.",
    "A verdadeira felicidade vem de fazer o que você ama.",
    "A mudança começa quando você decide dar o primeiro passo.",
    "Você é o único responsável pela sua felicidade.",
    "Nada é mais motivador do que ver o esforço gerar resultados.",
    "A vida é feita de escolhas. Escolha ser feliz.",
    "Cada amanhecer é uma nova chance de recomeçar.",
    "A força não vem do que você pode fazer, mas do que você pensa que não pode.",
    "Quem quer, dá um jeito. Quem não quer, dá desculpas.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Coragem não é a ausência do medo, mas a capacidade de seguir em frente apesar dele.",
    "Desafios são oportunidades disfarçadas.",
    "O amanhã é uma página em branco, e você é o autor.",
    "Sonhe grande, comece pequeno, mas nunca pare.",
    "A felicidade não é algo pronto, ela vem das suas ações.",
    "Ação é a chave para transformar seus sonhos em realidade.",
    "O sucesso exige dedicação, sacrifício e um pouco de coragem.",
    "Acredite em seu potencial e faça acontecer.",
    "Você nunca está sozinho quando segue seus sonhos.",
    "Cada pequeno passo te aproxima mais do seu grande objetivo.",
    "A única maneira de fazer um excelente trabalho é amar o que você faz.",
    "Acredite que você pode, e você já está no caminho para o sucesso.",
    "O medo é um obstáculo, mas a coragem é o que te leva além.",
    "Se você quer conquistar grandes coisas, deve estar disposto a sair da sua zona de conforto.",
    "A felicidade é a soma das pequenas conquistas diárias.",
    "Quem tem foco não se perde no caminho.",
    "O sucesso começa quando você começa.",
    "Não tenha medo de falhar, tenha medo de não tentar.",
    "Grandes realizações começam com pequenos passos de coragem.",
    "A vida te desafia, mas a vitória te recompensa.",
    "Continue, não desista, o melhor está por vir.",
    "Nunca subestime o poder de uma atitude positiva.",
    "O fracasso é apenas o começo de um novo aprendizado.",
    "Quem acredita sempre alcança.",
    "Seja forte, seja corajoso, seja você.",
    "O sucesso não é sobre vencer os outros, é sobre vencer a si mesmo.",
    "Seja persistente. Cada erro é uma lição para o sucesso.",
    "Você nunca saberá do que é capaz até tentar.",
    "Cada novo dia traz uma nova chance de vencer.",
    "O sucesso é para aqueles que nunca desistem, mesmo quando as coisas ficam difíceis.",
    "Acredite no seu sonho e vá atrás dele com tudo.",
    "Não espere por um momento perfeito. Faça o momento perfeito.",
    "O melhor momento para agir é agora.",
    "Não há limites para o que você pode alcançar quando acredita em si mesmo.",
    "Acredite, o impossível só leva mais tempo.",
    "Cada esforço te aproxima de um grande resultado.",
    "Você tem em suas mãos o poder de criar o seu próprio futuro.",
    "Transforme a adversidade em força e sabedoria.",
    "A jornada é difícil, mas a recompensa é grandiosa.",
    "Seu maior inimigo é o seu medo, sua maior arma é sua coragem.",
    "Faça do impossível algo possível.",
    "A vitória é a soma de perseverança, paciência e esforço.",
    "Você não chega ao sucesso sem antes passar pelo fracasso.",
    "A felicidade não é um destino, é uma maneira de viajar.",
    "Seja a mudança que você deseja ver no mundo.",
    "O único limite para os nossos sonhos somos nós mesmos.",
    "A única coisa que te impede de chegar lá é a sua dúvida.",
    "Cada dia é uma nova oportunidade de recomeçar.",
    "Transforme seus sonhos em realidade com esforço e dedicação.",
    "A vida é curta demais para esperar pelo momento perfeito. Faça acontecer.",
    "Seja resiliente. O sucesso te aguarda no final da jornada."
]

    
    if (index === undefined){
        return frases[Math.floor(Math.random() * frases.length)]
    }

    return frases[index]
}



module.exports = frasesAleatorias;
